<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>pl.komponentowe</groupId>
    <artifactId>programowanie-komponentowe</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>Model</module>
        <module>View</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.22</version>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>4.0.0-M16</version>
            </plugin>
        </plugins>
    </build>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>LICENSE</url>
            <distribution>repo</distribution>
            <comments>Simple license, code can be modified, and it does not contain warranty. </comments>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>254729</id>
            <name>Mikołaj Chlebicz</name>
            <email>254729@edu.p.lodz.pl</email>
        </developer>

        <developer>
            <id>254764</id>
            <name>Bartosz Horna</name>
            <email>254764@edu.p.lodz.pl</email>
        </developer>
    </developers>

    <description>Projekt grupy laboratoryjnej MKW_SR_1230_05</description>

    <distributionManagement>
        <site>
            <id>${project.artifactId}-site</id>
            <url>${project.baseUri}</url>
        </site>
    </distributionManagement>
</project>