package pl.komponentowe.model;

import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Set;

public class SudokuSolverTest {
    /**
     * Verifies that the board generated by SudokuSolver.solve
     * meets Sudoku rules - numbers do not repeat in row, column, and 3x3 block.
     */
    @Test
    void solveGameFillsEmptyBoardCorrectly() {
        SudokuBoard sudokuBoard = new SudokuBoard(new BacktrackingSudokuSolver());

        sudokuBoard.solveGame();

        // numbers in rows don't repeat
        for (int row = 0; row < 9; ++row) {
            Set<Integer> uniqueRowNumbers = new HashSet<>();
            for (int col = 0; col < 9; ++col)
                uniqueRowNumbers.add(sudokuBoard.get(row, col));

            assert(uniqueRowNumbers.size() == 9);
        }

        // numbers in columns don't repeat
        for (int col = 0; col < 9; ++col) {
            Set<Integer> uniqueColNumbers = new HashSet<>();
            for (int row = 0; row < 9; ++row)
                uniqueColNumbers.add(sudokuBoard.get(row, col));

            assert(uniqueColNumbers.size() == 9);
        }

        // numbers in 3x3 boxes don't repeat
        for (int xBox = 0; xBox < 3; ++xBox) {
            for (int yBox = 0; yBox < 3; ++yBox) {
                Set<Integer> uniqueBoxNumbers = new HashSet<>();
                for (int row = 3 * xBox; row < 3 * xBox + 3; ++row) {
                    for (int col = 3 * yBox; col < 3 * yBox + 3; ++col) {
                        uniqueBoxNumbers.add(sudokuBoard.get(row, col));
                    }
                }

                assert(uniqueBoxNumbers.size() == 9);
            }
        }
    }

    /**
     * Verifies that two consecutive calls of SudokuSolver.solve for an empty
     * board give different results.
     */
    @Test
    void solveGameOnEmptyBoardGivesDifferentResults() {
        SudokuBoard sudokuBoard = new SudokuBoard(new BacktrackingSudokuSolver());

        sudokuBoard.solveGame();
        int[] firstBoard = new int[81];
        for (int x = 0; x < 9; ++x) {
            for (int y = 0; y < 9; ++y) {
                firstBoard[y * 9 + x] = sudokuBoard.get(x, y);
            }
        }

        sudokuBoard.clear();
        sudokuBoard.solveGame();
        int[] secondBoard = new int[81];
        for (int x = 0; x < 9; ++x) {
            for (int y = 0; y < 9; ++y) {
                secondBoard[y * 9 + x] = sudokuBoard.get(x, y);
            }
        }

        boolean doBoardsDiffer = false;
        for (int i = 0; i < 81; ++i) {
            if (firstBoard[i] != secondBoard[i]) {
                doBoardsDiffer = true;
                break;
            }
        }

        assert(doBoardsDiffer);
    }

    /**
     * Verifies that manually entered numbers on the board remain unchanged
     * after calling SudokuSolver.solveGame.
     */
    @Test
    void solveGameKeepsExistingData() {
        SudokuBoard sudokuBoard = new SudokuBoard(new BacktrackingSudokuSolver());

        sudokuBoard.set(0, 0, 2);
        sudokuBoard.set(1, 0, 1);
        sudokuBoard.set(2, 0, 3);
        sudokuBoard.set(3, 0, 7);

        sudokuBoard.solveGame();

        assert(sudokuBoard.get(0, 0) == 2);
        assert(sudokuBoard.get(1, 0) == 1);
        assert(sudokuBoard.get(2, 0) == 3);
        assert(sudokuBoard.get(3, 0) == 7);
        assert(sudokuBoard.get(8, 8) != 0);
    }
}
